-- Número sequencial público da conta (usado na URL compartilhável)
ALTER TABLE public.contas
  ADD COLUMN IF NOT EXISTS numero bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL;

CREATE INDEX IF NOT EXISTS idx_contas_numero ON public.contas (numero);

COMMENT ON COLUMN public.contas.numero IS 'Identificador sequencial da conta para URLs compartilháveis.';
